export const GET_POKEMONS = 'GET_POKEMONS';
export const GET_POKEMON = 'GET POKEMON';
export const PROBABILITY_POKEMON = 'PROBABILITY_POKEMON';
export const CAUGHT_POKEMON = 'CAUGHT_POKEMON';
export const MY_POKEMONS = 'MY_POKEMONS';
export const RENAME_POKEMON = 'RENAME_POKEMON';
export const CHECK_NUMBER = 'CHECK_NUMBER';
export const RELEASE_POKEMON = 'RELEASE_POKEMON';

export const SET_GET_POKEMONS = 'SET_GET_POKEMONS';
export const SET_GET_POKEMON = 'SET_GET_POKEMON';
export const SET_PROBABILITY_POKEMON = 'SET_PROBABILITY_POKEMON';
export const RESET_PROBABILITY_POKEMON = 'RESET_PROBABILITY_POKEMON';
export const SET_CAUGHT_POKEMON = 'SET_CAUGHT_POKEMON';
export const SET_MY_POKEMONS = 'SET_MY_POKEMONS';
export const SET_RENAME_POKEMON = 'SET_RENAME_POKEMON';
export const SET_RELEASE_POKEMON = 'SET_RELEASE_POKEMON';
